services:
  - type: web
    name: stock-dashboard-realtime-poc
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: PUSH_TOKEN
        sync: false
